name: development
channels:
  - conda-forge
  - defaults
dependencies:
  - pip:
    - pip
    - numpy==1.23.4 #1.18.5
    - sentencepiece==0.1.97
    - timm==0.6.12
    - fairscale==0.4.13
    - opencv-python==4.7.0.68
    - flashtext==2.7
    - openai==0.26.5
    - torchvision==0.12.0
    - torchaudio==0.11.0
    - azure-storage-file-datalake==12.7.0
    - transformers==4.26.1
    - pyarrow==11.0.0
    - graphframes==0.6
    - spacy==3.2.4
    - azure-search-documents==11.4.0b3
    - fuzzywuzzy==0.18.0
    - python-Levenshtein==0.21.0
